
  <div class="adventure-island-container">
    <div class="clouds">
        <div class="bg"></div>
    </div>
    <div class="mountains">
        <div class="bg"></div>
    </div>
    <div class="trees">
        <div class="bg"></div>
    </div>
    <div class="bushes">
        <div class="bg"></div>
    </div>
    <div class="lawn">
        <div class="bg"></div>
    </div>
    <div class="scroll">
        <div class="bg"></div>
    </div>
</div>
